[build]
builder = "nixpacks"
builderSettings = { nodeVersion = "18.x" }
buildCommand = "cd frontend && npm install && npm run build && cd ../backend && npm install --sqlite=/usr --sqlite_libname=sqlite3 --omit=dev"

[deploy]
startCommand = "cd backend && npm start"